
# Site settings
title: Wang Wenhui William
name: Wang Wenhui William
subtitle: PhD Candidate
email: whwang@connect.hku.hk
description: >
  PhD Candidate
baseurl: ""
url: "https://wangwhw.github.io/"
github_username:  wangwhw
disqus_baseurl: "https://wangwhw.github.io/"
disqus_shortname: https-wangwhw-github-io
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Wang Wenhui William"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:

  - name: ResearchGate
    icon: ResearchGate
    username: Wenhui Wang
    url: https://www.researchgate.net/profile/Wenhui_Wang9
    desc: Connect with me on LinkedIn
    share: true
